version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: base # Usamos 'base' para dev para poder instalar gems de dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && yarn install && ./bin/dev"
    volumes:
      - .:/rails # Monta o código local no container
      - bundle_cache:/usr/local/bundle # Cache de gems
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      # Importante para SQLite funcionar bem no container
      - DATABASE_URL=sqlite3:/rails/storage/development.sqlite3
    # Mapeamento de usuário para evitar problemas de permissão no Podman
    userns_mode: keep-id

volumes:
  bundle_cache: